name: InventoryLogger
version: 1.0.2
author: zPirroZ3007
description: This plugin logs the players' inventories so you can see them.
main: me.pirro.inventorylogger.Main
api-version: 1.13

commands:
  inventorylogs:
    description: Main command of the plugin
    aliases:
      - invlogs
      - inventorylogs
      - invlog